version: "3"

services:
        influx:
                image: influxdb:2.0
                volumes:
                        - ./influx-data:/var/lib/influxdb2
                ports:
                        - 8086:8086
                environment:
                        - DOCKER_INFLUXDB_INIT_USERNAME="${INFLUX_USERNAME}"
                        - DOCKER_INFLUXDB_INIT_PASSWORD="${INFLUX_PASSWORD}"
                        - DOCKER_INFLUXDB_INIT_ORG="${INFLUX_ORG}"
                        - DOCKER_INFLUXDB_INIT_BUCKET="${INFLUX_BUCKET}"
                hostname: influx
        domain-watcher:
                image: domain-watcher:latest
                volumes:
                        - ./domain-watcher/target:/usr/src/app/target
                        - ./domain-watcher:/usr/src/app
                build:
                        context: ./domain-watcher
