version: "3"

services:
        time-series-db:
                image: questdb/questdb
                ports:
                        - "9009:9009" # InfluxDB line protocol
                        - "9000:9000" # REST API and Web Console
        domain-watcher:
                image: domain-watcher:latest
                build: ./domain-watcher
                environment:
                        DOMAIN_WATCHER_DOMAIN_LIST: "domains.txt"
                        DOMAIN_WATCHER_KAFKA_BROKERS: "kafka:9092"
                        DOMAIN_WATCHER_CONCURRENT_REQUESTS: 16384 # Batch request size.
                        DOMAIN_WATCHER_WAIT_TIME: 10 # Seconds to wait for each batch of requests.
                depends_on:
                        - kafka
        zookeeper:
                image: wurstmeister/zookeeper
                ports:
                        - "2181:2181"
        kafka:
                image: wurstmeister/kafka
                ports:
                        - "9092:9092"
                environment:
                        KAFKA_ADVERTISED_PORT: 9092
                        KAFKA_ADVERTISED_HOST_NAME: "kafka"
                        KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
                        KAFKA_CREATE_TOPICS: "pingevents:1:1"
                depends_on:
                        - zookeeper
        ingester:
                image: ingester
                build: ./ingester
                depends_on:
                        - kafka
                        - "time-series-db"
                environment:
                        DB_USERNAME: "${QUERYDB_USERNAME}"
                        DB_PASSWORD: "${QUERYDB_PASSWORD}"
                        DB_DATABASE: "${QUERYDB_DATABASE}"
                        DB_HOST: "${QUERYDB_HOST}"
                        DB_PORT: 9009
                        KAFKA_BROKERS: "kafka:9092"
        api:
                image: api
                build: ./api
                depends_on:
                        - "time-series-db"
