/*
 * Domain Tracker
 *
 * This is the domain tracker API that provides details about PingEvents made to various domains.
 *
 * API version: 1.0.0
 * Contact: itsme@aalekhpatel.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ApiResponse struct {

	Code int32 `json:"code,omitempty"`

	Type_ string `json:"type,omitempty"`

	Message string `json:"message,omitempty"`
}
