/*
 * Domain Tracker
 *
 * This is the domain tracker API that provides details about PingEvents made to various domains.
 *
 * API version: 1.0.0
 * Contact: itsme@aalekhpatel.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PingEvent struct {

	Id int64 `json:"id,omitempty"`

	Url string `json:"url,omitempty"`

	Timestamp string `json:"timestamp,omitempty"`

	ResponseCode int32 `json:"response_code,omitempty"`

	// (response time is in nanosecond precision)
	ResponseTime int64 `json:"response_time,omitempty"`
}
